### ISSUE TITLE
Generic parameter 'T' could not be inferred by jsonEncoder

### ISSUE THREAD

**Issue by kornerr** [commercetools/commercetools-ios-sdk#158]
Hi.

Xcode 9.3 can't build Commercetools 0.7.4:
```
.../Pods/Commercetools/Source/Commercetools.swift:144:43: error: generic parameter 'T' could not be inferred
        let jsonProfile = try jsonEncoder.encode(profile)
                                          ^
```

This is a minimal Xcode project with Commercetools pod only.

Changing `public func signUpCustomer(_ profile: [String: Any]` (in the same file) to `public func signUpCustomer(_ profile: [String: String]` fixes the error but I'm not sure if it's correct.

**Comment by nikola-mladenovic** [comment]
Thank you, the new 0.7.5 release will have latest Xcode support and some new API features incorporated. It will be in CocoaPods trunk in a day or two, and in the meantime you can specify master branch for Commercetools SDK in your podfile.

**Comment by nikola-mladenovic** [comment]
@kornerr try running `pod repo update` and then `pod update` to get the latest version of the SDK (0.7.5).

Let me know if this fixed your issue.

**Comment by kornerr** [comment]
Works like a charm. Thanks.
