### ISSUE TITLE
Paging issue: Different products are returned when performing the same search

### ISSUE THREAD

**Issue by kornerr** [commercetools/commercetools-ios-sdk#160]
Hi.

I want to implement paging in my application, however, `ProductProjection.search` (with the same `categories.id:"<categoryId>"` filter) returns different products each request.

How would I implement paging if CommerceTools SDK can't guarantee the same order of products?

Thanks.

**Comment by nikola-mladenovic** [comment]
It'd be best to set at least one value for the `sort` array. That should solve your issue.

**Comment by damarna85** [comment]
If you use the search with no text and only the categories filter, you are getting non deterministic responses from the API every team you request the search. So to get a deterministic responses, as @nikola-mladenovic mentioned, you will have to add a sort (the createdAt field is what I commonly use in this kind of scenarios).

**Comment by kornerr** [comment]
Thanks. Works like a charm!
