### ISSUE TITLE
Support X-External-User-ID header

### ISSUE THREAD

**Issue by nikola-mladenovic** [commercetools/commercetools-ios-sdk#174]
Since client applications can now use a new HTTP header, X-External-User-ID, when making API calls to track changes initiated by a specific user’s actions, we should add support for thta in the SDK.

@cneijenhuis should we include any limitations on this, or simply let the app set this header value at any point in time, and use it for all subsequent requests, until it's unset?

**Comment by cneijenhuis** [comment]
I haven't been working on that feature. My guess is that keeping it for all subsequent requests is fine.
