### ISSUE TITLE
Define our Documentation strategy

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-ios-sdk#21]
What do we want to document and where?
We definitely want to fill the `README.md` with some info on getting started.
Where should additional reference info go? Should we use something like CocoaDocs or stick to `.md` files?
Can we use our tests as examples?

**Comment by nikola-mladenovic** [comment]
We should definitely use CocoaDocs, but also we can use [jazzy](https://github.com/realm/jazzy) - it hooks into Clang and SourceKit to use the AST representation of our code and its comments;

It generates Apple like documentation pages, and we can have the output html available on our ghpages.

**Comment by cneijenhuis** [comment]
I've used neither and am fine with both :)

Can one of the two embed our test cases into the documentation? E.g. like here in the JVM SDK: https://github.com/sphereio/sphere-jvm-sdk/blob/67ed19ea22d2c1c6883bc57ca1124cade287cbc8/commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/GettingStarted.java#L40
