### ISSUE TITLE
Migrate repo to commercetools organization before it's released

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-ios-sdk#70]
I know, I'm annoying with the topic. 

But it hurts a bit so see even new projects pop up in the "old" org while it's been defined now that the OSS ecosystem is to be consolidated in the commercetools organization.

**Comment by nikola-mladenovic** [comment]
We can perform the migration after our next CocoaPods release, because our current pod version is specified to be on this repository.
