### ISSUE TITLE
Use a standard convention UserAgent HTTP header

### ISSUE THREAD

**Issue by nikola-mladenovic** [commercetools/commercetools-ios-sdk#79]
Main difference between other SDKs and a mobile SDK, is that in a mobile SDK, a solution name represents the name of the app using the SDK, and the solution version, would also represent the AppStore version of the app using the SDK.

In the example of our Sunrise app, this is how minimum User-Agent would look like: `commercetools-ios-sdk/0.3.0 Sunrise/0.1.1 (iOS/10.0.2)`.

If we add the solution info, it'd become: `commercetools-ios-sdk/0.3.0 Sunrise/0.1.1 (iOS/10.0.2) Sunrise/0.1.1 (+https://github.com/commercetools/commercetools-sunrise-ios; +nikola.mladenovic@commercetools.com)`

@nkuehn @cneijenhuis - WDYT, are you OK with the above?

**Comment by nkuehn** [comment]
more or less. It's a bit simpler on iOS as there is not much diversity inside iOS. 

The second block is intended to be the raw runtime of the code, so the minimal version if the user code does not pass any info to the SDK: 
`commercetools-ios-sdk/0.3.0 iOS/10.0.2`

Plus, if solution info is added (for our sample app)
`commercetools-ios-sdk/0.3.0 iOS/10.0.2 Sunrise/0.1.1 (+https://github.com/commercetools/commercetools-sunrise-ios)` (we  don't need contact data for our own apps, we know our colleagues)


For an invented client app (with URL only):
`commercetools-ios-sdk/0.3.0 iOS/10.0.2 mySuperShopApp/0.2`
 
Including  contact data:
`commercetools-ios-sdk/0.3.0 iOS/10.0.2 mySuperShopApp/0.2 (+support@mySuperShopApp.com)`

does that make sense?

**Comment by nikola-mladenovic** [comment]
Yes, makes sense 👍
