### ISSUE TITLE
Add models for all update actions supported in the SDK

### ISSUE THREAD

**Issue by nikola-mladenovic** [commercetools/commercetools-ios-sdk#83]
My proposal for introducing update action models in the SDK:

- `UpdateEndpoint` protocol will get an `associatedtype UpdateAction: JSONRepresentable`.
- `JSONRepresentable` protocol introduced here specifies only one property:
```swift
public protocol JSONRepresentable {
    var toJSON: [String: Any] { get }
}
```
- Newly introduced method in `UpdateEndpoint` will look like this:
```swift
static func update(_ id: String, actions: UpdateActions<UpdateAction>, expansion: [String]?, result: @escaping (Result<ResponseType>) -> Void)
```
- `UpdateActions` is a simple struct skeleton for update actions:
```swift
public struct UpdateActions<T: JSONRepresentable>: JSONRepresentable {

    // MARK: - Properties

    var version: UInt
    var actions: [T]

    public var toJSON: [String: Any] {
        return ["version": version, "actions": actions.map({ $0.toJSON })]
    }
}
```
- Endpoints which support models for update actions shall specify `typealias` for `UpdateAction` associated type.

Brief illustration on `Cart` example:
```swift
open class Cart: QueryEndpoint, ByIdEndpoint, CreateEndpoint, UpdateEndpoint, DeleteEndpoint, Mappable {        
    // ...
    public typealias UpdateAction = CartUpdateAction    
	// ...
}

public enum CartUpdateAction: JSONRepresentable {

    case addLineItem(options: AddLineItemOptions)
    // ...

    public var toJSON: [String: Any] {
        switch self {
        case .addLineItem(let options):
            var optionsJSON = Mapper<AddLineItemOptions>().toJSON(options)
            optionsJSON["action"] = "addLineItem"
            return optionsJSON
        // case ...
        }
    }
}

public struct AddLineItemOptions: Mappable {

    // MARK: - Properties

    var productId: String?
    var variantId: Int?
    var quantity: UInt?
    var supplyChannel: Reference<Channel>?
    // ...
}
```

And finally, the consumption of this update action:
```swift
var options = AddLineItemOptions()
options.productId = productId
options.variantId = 1
let updateActions = UpdateActions(version: 3, actions: [CartUpdateAction.addLineItem(options: options)])

TestCart.update(id, actions: updateActions, result: { result in
    // ...
})
```

The benefit of having an `enum` with all possible update actions for an endpoint, IMO makes it easy for the user to quickly get to the desired action and get autocompletion.
The reason for placing the `enum` associated value into a `struct` named _SomeUpdateAction*Options*_ is to avoid having really long lines when instantiating `UpdateAction`.

This is just my view, @cneijenhuis WDYT?

**Comment by cneijenhuis** [comment]
Looks good to me! The existing update method with pure JSON will remain, I guess?

**Comment by nikola-mladenovic** [comment]
Yes, absolutely 👍
